import Zeus from '../assets/quants/zeus.svg';
import Minuteman from '../assets/quants/minuteman.svg';
import Apollo from '../assets/quants/apollo.svg';
import Aphrodite from '../assets/quants/aphrodite.svg';
import Guardian from '../assets/quants/guardian.svg';
import Bhishma from '../assets/quants/nakula.svg';
import Demeter from '../assets/quants/apollo.svg';
import Arya from '../assets/quants/arya_stark.svg';
import Cersei from '../assets/quants/cersei_lannister.svg';
import Daenerys from '../assets/quants/daenerys_targaryen.svg';
import Hound from '../assets/quants/the_hound.svg';
import Poseidon from '../assets/quants/poseidon.svg';
import MarcoPolo from '../assets/quants/marko_polo.svg';
import VascodaGama from '../assets/quants/vasco_da_gama.svg';
import Columbus from '../assets/quants/wizard.svg';
import ZeusGreat from '../assets/quants/priam.svg';
import Xerxes from '../assets/quants/xerxes.svg';
import Aristotle from '../assets/quants/aristotle.svg';
import Archimedes from '../assets/quants/socrates.svg';
import Matador from '../assets/quants/matador.svg';
import Hera from '../assets/quants/hera.svg';
import Pythagoras from '../assets/quants/pythagoras.svg';
import Athena from '../assets/quants/athena.svg';
import Achilles from '../assets/quants/athena.svg';
import Odysseus from '../assets/quants/hector.svg';
import Zeus1 from '../assets/quants/ares.svg';
import Hercules from '../assets/quants/hercules.svg';

const quants = [
  {
    imgUrl: '/static/images/quants/zeus.svg',
    tags: ['Bullish'],
    startdate: '2022-11-12T10:58:15.903Z',
    _id: 25,
    IMAGELOGO: Zeus,
    name: 'Zeus',
    description:
      "Zeus is the world's first quantitative algorithm that buildings a portfolio by investing daily into direct stocks",
    price: 100,
    status: 'active',
    stocks: [
      {
        _id: '637254f9ee6eac4a21150ce5',
        name: 'Rashtriya Chemicals & Fertilizers Ltd.',
        series: 'EQ',
        symbol: 'RCF',
        ISIN: 'INE027A01015',
      },
      {
        _id: '637254f9ee6eac4a21150ce6',
        name: 'CESC Ltd.',
        series: 'EQ',
        symbol: 'CESC',
        ISIN: 'INE486A01021',
      },
      {
        _id: '637254f9ee6eac4a21150ce7',
        name: 'Tata Steel Ltd.',
        series: 'EQ',
        symbol: 'TATASTEEL',
        ISIN: 'INE081A01012',
      },
      {
        _id: '637254f9ee6eac4a21150ce8',
        name: 'Steel Authority of India Ltd.',
        series: 'EQ',
        symbol: 'SAIL',
        ISIN: 'INE114A01011',
      },
      {
        _id: '637254f9ee6eac4a21150ce9',
        name: 'Kalyan Jewellers India Ltd.',
        series: 'EQ',
        symbol: 'KALYANKJIL',
        ISIN: 'INE303R01014',
      },
      {
        _id: '637254f9ee6eac4a21150cea',
        name: 'The New India Assurance Company Ltd.',
        series: 'EQ',
        symbol: 'NIACL',
        ISIN: 'INE470Y01017',
      },
      {
        _id: '637254f9ee6eac4a21150ceb',
        name: 'Indian Oil Corporation Ltd.',
        series: 'EQ',
        symbol: 'IOC',
        ISIN: 'INE242A01010',
      },
      {
        _id: '637254f9ee6eac4a21150cec',
        name: 'GAIL (India) Ltd.',
        series: 'EQ',
        symbol: 'GAIL',
        ISIN: 'INE129A01019',
      },
      {
        _id: '637254f9ee6eac4a21150ced',
        name: 'Gujarat Pipavav Port Ltd.',
        series: 'EQ',
        symbol: 'GPPL',
        ISIN: 'INE517F01014',
      },
      {
        _id: '637254f9ee6eac4a21150cee',
        name: 'L&T Finance Holdings Ltd.',
        series: 'EQ',
        symbol: 'L&TFH',
        ISIN: 'INE498L01015',
      },
    ],
    strategy: 'tiger',
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '637254f9ee6eac4a21150cef',
        categoryId: {
          status: 'active',
          _id: 9,
          name: 'Invest Daily',
          description: 'Invest Daily',
        },
      },
    ],
    subCategories: [
      {
        _id: '637254f9ee6eac4a21150cf0',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '637254f9ee6eac4a21150cf1',
        subCategoryId: 12,
        subCategoryName: 'Fixed Income',
      },
      {
        _id: '637254f9ee6eac4a21150cf2',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '637254f9ee6eac4a21150cf3',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '637254f9ee6eac4a21150cf4',
        subCategoryId: 10,
        subCategoryName: 'Under Priced',
      },
      {
        _id: '637254f9ee6eac4a21150cf5',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '637254f9ee6eac4a21150cf6',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '637254f9ee6eac4a21150cf7',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
    ],
    functionality: [
      {
        _id: '637254f9ee6eac4a21150cf8',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '637254f9ee6eac4a21150cf9',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/minuteman.svg',
    tags: ['Bullish'],
    startdate: '2022-11-12T10:58:15.903Z',
    _id: 26,
    IMAGELOGO: Minuteman,
    name: 'Minuteman',
    description:
      'Minuteman is the powered by the world first quantitative model which invests directly in equities on a daily basis',
    price: 50,
    status: 'active',
    stocks: [
      {
        _id: '63725b93ee6eac4a21150d4d',
        name: 'Infibeam Avenues Ltd.',
        series: 'EQ',
        symbol: 'INFIBEAM',
        ISIN: 'INE483S01020',
      },
      {
        _id: '63725b93ee6eac4a21150d4e',
        name: 'Indian Railway Finance Corporation Ltd.',
        series: 'EQ',
        symbol: 'IRFC',
        ISIN: 'INE053F01010',
      },
      {
        _id: '63725b93ee6eac4a21150d4f',
        name: 'MMTC Ltd.',
        series: 'EQ',
        symbol: 'MMTC',
        ISIN: 'INE123F01029',
      },
      {
        _id: '63725b93ee6eac4a21150d50',
        name: 'TV18 Broadcast Ltd.',
        series: 'EQ',
        symbol: 'TV18BRDCST',
        ISIN: 'INE886H01027',
      },
      {
        _id: '63725b93ee6eac4a21150d51',
        name: 'Trident Ltd.',
        series: 'EQ',
        symbol: 'TRIDENT',
        ISIN: 'INE064C01022',
      },
      {
        _id: '63725b93ee6eac4a21150d52',
        name: 'SJVN Ltd.',
        series: 'EQ',
        symbol: 'SJVN',
        ISIN: 'INE002L01015',
      },
      {
        _id: '63725b93ee6eac4a21150d53',
        name: 'PNB Housing Finance Ltd.',
        series: 'EQ',
        symbol: 'PNBHOUSING',
        ISIN: 'INE572E01012',
      },
      {
        _id: '63725b93ee6eac4a21150d54',
        name: 'NHPC Ltd.',
        series: 'EQ',
        symbol: 'NHPC',
        ISIN: 'INE848E01016',
      },
      {
        _id: '63725b93ee6eac4a21150d55',
        name: 'Housing & Urban Development Corporation Ltd.',
        series: 'EQ',
        symbol: 'HUDCO',
        ISIN: 'INE031A01017',
      },
    ],
    strategy: 'tiger_1',
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '63725b93ee6eac4a21150d56',
        categoryId: {
          status: 'active',
          _id: 9,
          name: 'Invest Daily',
          description: 'Invest Daily',
        },
      },
    ],
    subCategories: [
      {
        _id: '63725b93ee6eac4a21150d57',
        subCategoryId: 12,
        subCategoryName: 'Fixed Income',
      },
      {
        _id: '63725b93ee6eac4a21150d58',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '63725b93ee6eac4a21150d59',
        subCategoryId: 13,
        subCategoryName: 'Market Making',
      },
      {
        _id: '63725b93ee6eac4a21150d5a',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '63725b93ee6eac4a21150d5b',
        subCategoryId: 8,
        subCategoryName: 'Bluechips',
      },
      {
        _id: '63725b93ee6eac4a21150d5c',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '63725b93ee6eac4a21150d5d',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '63725b93ee6eac4a21150d5e',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
    ],
    functionality: [
      {
        _id: '63725b93ee6eac4a21150d5f',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '63725b93ee6eac4a21150d60',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/apollo.svg',
    tags: ['Bearish', 'Bullish'],
    startdate: '2022-07-11T07:00:31.165Z',
    _id: 21,
    IMAGELOGO: Apollo,
    name: 'Apollo',
    description:
      'Apollo is a Continuous Nifty Futures Long Short Quant. Designed to weather all market conditions',
    price: 250000,
    status: 'active',
    stocks: [
      {
        _id: '62cd8753fdf57d7e9f538a3c',
        name: 'Nifty Futures',
        series: 'FNO',
        symbol: 'NIFTY 28 Jul 2022',
        ISIN: 'INE000000001',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '62cd8753fdf57d7e9f538a3d',
        categoryId: {
          status: 'active',
          _id: 6,
          name: 'Index Continous Futures',
          description: 'Index Continous Futures',
        },
      },
    ],
    subCategories: [
      {
        _id: '62cd8753fdf57d7e9f538a3e',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '62cd8753fdf57d7e9f538a3f',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '62cd8753fdf57d7e9f538a40',
        subCategoryId: 11,
        subCategoryName: 'Continous Futures',
      },
      {
        _id: '62cd8753fdf57d7e9f538a41',
        subCategoryId: 12,
        subCategoryName: 'Fixed Income',
      },
    ],
    functionality: [
      {
        _id: '62cd8753fdf57d7e9f538a42',
        functionalityId: {
          status: 'active',
          _id: 2,
          name: 'Long & Short',
          description: 'Long & Short',
        },
        functionalityName: 'Long & Short',
      },
      {
        _id: '62cd8753fdf57d7e9f538a43',
        functionalityId: {
          status: 'active',
          _id: 4,
          name: 'Arbitrage',
          description: 'Arbitrage',
        },
        functionalityName: 'Arbitrage',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    futures: true,
    strategy: 'cheetah_long_short',
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/aphrodite.svg',
    tags: ['Bullish', 'Bearish'],
    startdate: '2022-07-11T07:00:31.165Z',
    _id: 22,
    IMAGELOGO: Aphrodite,
    name: 'Aphrodite',
    description:
      'Aphrodite is a Bank Nifty Continous Long Short Futures Trading Quant. Designed to weather the market in all conditions',
    price: 250000,
    status: 'active',
    stocks: [
      {
        _id: '62cd8a9ffdf57d7e9f538a73',
        name: 'Bank Nifty Futures',
        series: 'FNO',
        symbol: 'BANKNIFTY 28 Jul 2022',
        ISIN: 'INE000000004',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '62cd8a9ffdf57d7e9f538a74',
        categoryId: {
          status: 'active',
          _id: 6,
          name: 'Index Continous Futures',
          description: 'Index Continous Futures',
        },
      },
    ],
    subCategories: [
      {
        _id: '62cd8a9ffdf57d7e9f538a75',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '62cd8a9ffdf57d7e9f538a76',
        subCategoryId: 11,
        subCategoryName: 'Continous Futures',
      },
      {
        _id: '62cd8a9ffdf57d7e9f538a77',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '62cd8a9ffdf57d7e9f538a78',
        functionalityId: {
          status: 'active',
          _id: 2,
          name: 'Long & Short',
          description: 'Long & Short',
        },
        functionalityName: 'Long & Short',
      },
      {
        _id: '62cd8a9ffdf57d7e9f538a79',
        functionalityId: {
          status: 'active',
          _id: 4,
          name: 'Arbitrage',
          description: 'Arbitrage',
        },
        functionalityName: 'Arbitrage',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    futures: true,
    ' strategy': 'cheetah_long_short',
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/guardian.svg',
    tags: ['Bearish', 'Bullish'],
    startdate: '2022-07-11T07:00:31.165Z',
    _id: 23,
    IMAGELOGO: Guardian,
    name: 'Guardian',
    description:
      'Guardian is a Continous SBI Stock Futures  Long Short Trading Quant. Designed to weather the market in all conditions',
    price: 300000,
    status: 'active',
    stocks: [
      {
        _id: '62cd8beafdf57d7e9f538a8c',
        name: 'SBI Futures',
        series: 'FNO',
        symbol: 'SBIN 28 Jul 2022',
        ISIN: 'INE000000007',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '62cd8beafdf57d7e9f538a8d',
        categoryId: {
          status: 'active',
          _id: 6,
          name: 'Index Continous Futures',
          description: 'Index Continous Futures',
        },
      },
    ],
    subCategories: [
      {
        _id: '62cd8beafdf57d7e9f538a8e',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '62cd8beafdf57d7e9f538a8f',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
      {
        _id: '62cd8beafdf57d7e9f538a90',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '62cd8beafdf57d7e9f538a91',
        subCategoryId: 14,
        subCategoryName: 'Arbitrage',
      },
      {
        _id: '62cd8beafdf57d7e9f538a92',
        subCategoryId: 11,
        subCategoryName: 'Continous Futures',
      },
    ],
    functionality: [
      {
        _id: '62cd8beafdf57d7e9f538a93',
        functionalityId: {
          status: 'active',
          _id: 2,
          name: 'Long & Short',
          description: 'Long & Short',
        },
        functionalityName: 'Long & Short',
      },
      {
        _id: '62cd8beafdf57d7e9f538a94',
        functionalityId: {
          status: 'active',
          _id: 4,
          name: 'Arbitrage',
          description: 'Arbitrage',
        },
        functionalityName: 'Arbitrage',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    futures: true,
    strategy: 'cheetah_long_short',
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/nakula.svg',
    tags: ['Bearish', 'Bullish'],
    startdate: '2022-07-11T07:00:31.165Z',
    _id: 24,
    IMAGELOGO: Bhishma,
    name: 'Bhishma Pitamah',
    description:
      'Bhishma Pitamah is a Continous Reliance Stock Futures Trading Quant, designed to weather the market in all conditions',
    price: 300000,
    status: 'active',
    stocks: [
      {
        _id: '62cd8c9efdf57d7e9f538abe',
        name: 'Reliance Futures',
        series: 'FNO',
        symbol: 'RELIANCE 28 Jul 2022',
        ISIN: 'INE000000010',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '62cd8c9efdf57d7e9f538abf',
        categoryId: {
          status: 'active',
          _id: 6,
          name: 'Index Continous Futures',
          description: 'Index Continous Futures',
        },
      },
    ],
    subCategories: [
      {
        _id: '62cd8c9efdf57d7e9f538ac0',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '62cd8c9efdf57d7e9f538ac1',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '62cd8c9efdf57d7e9f538ac2',
        subCategoryId: 11,
        subCategoryName: 'Continous Futures',
      },
      {
        _id: '62cd8c9efdf57d7e9f538ac3',
        subCategoryId: 12,
        subCategoryName: 'Fixed Income',
      },
    ],
    functionality: [
      {
        _id: '62cd8c9efdf57d7e9f538ac4',
        functionalityId: {
          status: 'active',
          _id: 2,
          name: 'Long & Short',
          description: 'Long & Short',
        },
        functionalityName: 'Long & Short',
      },
      {
        _id: '62cd8c9efdf57d7e9f538ac5',
        functionalityId: {
          status: 'active',
          _id: 5,
          name: 'Hedged',
          description: 'Hedged',
        },
        functionalityName: 'Hedged',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    futures: true,
    strategy: 'cheetah_long_short',
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/apollo.svg',
    tags: ['Bearish', 'Bullish'],
    startdate: '2022-07-11T07:00:31.165Z',
    _id: 27,
    IMAGELOGO: Demeter,
    name: 'Demeter',
    description:
      'Demeter is a Continuous Tata Steel Futures Long Short Quant. Designed to weather all market conditions',
    price: 250000,
    status: 'active',
    stocks: [
      {
        _id: '62cd8753fdf57d7e9f538a3c',
        name: 'TATASTEEL Futures',
        series: 'FNO',
        symbol: 'TATASTEEL 28 Jul 2022',
        ISIN: 'INE000000001',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '62cd8753fdf57d7e9f538a3d',
        categoryId: {
          status: 'active',
          _id: 6,
          name: 'Index Continous Futures',
          description: 'Index Continous Futures',
        },
      },
    ],
    subCategories: [
      {
        _id: '62cd8753fdf57d7e9f538a3e',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '62cd8753fdf57d7e9f538a3f',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '62cd8753fdf57d7e9f538a40',
        subCategoryId: 11,
        subCategoryName: 'Continous Futures',
      },
      {
        _id: '62cd8753fdf57d7e9f538a41',
        subCategoryId: 12,
        subCategoryName: 'Fixed Income',
      },
    ],
    functionality: [
      {
        _id: '62cd8753fdf57d7e9f538a42',
        functionalityId: {
          status: 'active',
          _id: 2,
          name: 'Long & Short',
          description: 'Long & Short',
        },
        functionalityName: 'Long & Short',
      },
      {
        _id: '62cd8753fdf57d7e9f538a43',
        functionalityId: {
          status: 'active',
          _id: 4,
          name: 'Arbitrage',
          description: 'Arbitrage',
        },
        functionalityName: 'Arbitrage',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    futures: true,
    strategy: 'cheetah_long_short',
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/arya_stark.svg',
    tags: ['Bullish', 'Breakout'],
    startdate: '2022-06-04T02:54:40.972Z',
    _id: 17,
    IMAGELOGO: Arya,
    _idold: '629ba1a20d8f441784cc768b',
    name: 'Arya',
    strategy: 'cheetah',
    description:
      'Arya, The stark whose heroics are still vivid in our minds, what a transformation. Likewise Investing in small-cap companies which have great potential is spotted by Arya, and she ensures the journey your investing journey is as exciting as her. You are in for a royal experience!',
    price: 100000,
    status: 'active',
    stocks: [
      {
        _id: '629ba1a20d8f441784cc768c',
        name: 'Aarti Industries Ltd.',
        series: 'EQ',
        symbol: 'AARTIIND',
        ISIN: 'INE769A01020',
      },
      {
        _id: '629ba1a20d8f441784cc768d',
        name: 'BSE Ltd.',
        series: 'EQ',
        symbol: 'BSE',
        ISIN: 'INE118H01025',
      },
      {
        _id: '629ba1a20d8f441784cc768e',
        name: 'Bharat Heavy Electricals Ltd.',
        series: 'EQ',
        symbol: 'BHEL',
        ISIN: 'INE257A01026',
      },
      {
        _id: '629ba1a20d8f441784cc768f',
        name: 'Balrampur Chini Mills Ltd.',
        series: 'EQ',
        symbol: 'BALRAMCHIN',
        ISIN: 'INE119A01028',
      },
      {
        _id: '629ba1a20d8f441784cc7690',
        name: 'Bata India Ltd.',
        series: 'EQ',
        symbol: 'BATAINDIA',
        ISIN: 'INE176A01028',
      },
      {
        _id: '629ba1a20d8f441784cc7691',
        name: 'E.I.D. Parry (India) Ltd.',
        series: 'EQ',
        symbol: 'EIDPARRY',
        ISIN: 'INE126A01031',
      },
      {
        _id: '629ba1a20d8f441784cc7692',
        name: 'Granules India Ltd.',
        series: 'EQ',
        symbol: 'GRANULES',
        ISIN: 'INE101D01020',
      },
      {
        _id: '629ba1a20d8f441784cc7693',
        name: 'Firstsource Solutions Ltd.',
        series: 'EQ',
        symbol: 'FSL',
        ISIN: 'INE684F01012',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '629ba1a20d8f441784cc7694',
        categoryId: {
          status: 'active',
          _id: 8,
          name: 'NIFTY Smallcap',
          description: 'NIFTY Smallcap',
        },
      },
    ],
    subCategories: [
      {
        _id: '629ba1a20d8f441784cc7695',
        subCategoryId: 10,
        subCategoryName: 'Under Priced',
      },
      {
        _id: '629ba1a20d8f441784cc7696',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '629ba1a20d8f441784cc7697',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '629ba1a20d8f441784cc7698',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
      {
        _id: '629ba1a20d8f441784cc7699',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
    ],
    functionality: [
      {
        _id: '629ba1a20d8f441784cc769a',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '629ba1a20d8f441784cc769b',
        functionalityId: {
          status: 'active',
          _id: 4,
          name: 'Arbitrage',
          description: 'Arbitrage',
        },
        functionalityName: 'Arbitrage',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/cersei_lannister.svg',
    tags: ['Arbitrage', 'Breakout', 'Bullish'],
    startdate: '2022-06-04T02:54:40.972Z',
    _id: 19,
    IMAGELOGO: Cersei,
    _idold: '629ba6ba0d8f441784cc7705',
    name: 'Cersei',
    strategy: 'cheetah',
    description:
      "Cersei, The Queen! But did you notice it takes twice as much effort to stay on the top, than the road down! Likewise, markets are not a day's game, long term and strategic action is required, watch Cersei do great things for you to prosper in the best emerging small-cap companies",
    price: 125000,
    status: 'active',
    stocks: [
      {
        _id: '629ba6ba0d8f441784cc7706',
        name: 'Mahindra Holidays & Resorts India Ltd.',
        series: 'EQ',
        symbol: 'MHRIL',
        ISIN: 'INE998I01010',
      },
      {
        _id: '629ba6ba0d8f441784cc7707',
        name: 'Equitas Holdings Ltd.',
        series: 'EQ',
        symbol: 'EQUITAS',
        ISIN: 'INE988K01017',
      },
      {
        _id: '629ba6ba0d8f441784cc7708',
        name: 'Happiest Minds Technologies Ltd.',
        series: 'EQ',
        symbol: 'HAPPSTMNDS',
        ISIN: 'INE419U01012',
      },
      {
        _id: '629ba6ba0d8f441784cc7709',
        name: 'ITC Ltd.',
        series: 'EQ',
        symbol: 'ITC',
        ISIN: 'INE154A01025',
      },
      {
        _id: '629ba6ba0d8f441784cc770a',
        name: 'Steel Authority of India Ltd.',
        series: 'EQ',
        symbol: 'SAIL',
        ISIN: 'INE114A01011',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '629ba6ba0d8f441784cc770b',
        categoryId: {
          status: 'active',
          _id: 8,
          name: 'NIFTY Smallcap',
          description: 'NIFTY Smallcap',
        },
      },
    ],
    subCategories: [
      {
        _id: '629ba6ba0d8f441784cc770c',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '629ba6ba0d8f441784cc770d',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '629ba6ba0d8f441784cc770e',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '629ba6ba0d8f441784cc770f',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '629ba6ba0d8f441784cc7710',
        subCategoryId: 7,
        subCategoryName: 'ESG',
      },
    ],
    functionality: [
      {
        _id: '629ba6ba0d8f441784cc7711',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '629ba6ba0d8f441784cc7712',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/daenerys_targaryen.svg',
    tags: ['Bullish', 'Breakout', 'Arbitrage'],
    startdate: '2022-06-04T02:54:40.972Z',
    _id: 18,
    IMAGELOGO: Daenerys,
    _idold: '629ba41c0d8f441784cc76d2',
    name: 'Daenerys',
    strategy: 'cheetah',
    description:
      'Daenerys, Same became the queen and claimed her rightful place, if observed deeply the biggest learning point in her journey has been the process, strategy and discipline. While Daenerys is in play you could see that mistakes and inefficiency are not her cups of tea but rather you get to learn how rewarding staying disciplined can be',
    price: 100000,
    status: 'active',
    stocks: [
      {
        _id: '629ba41c0d8f441784cc76d3',
        name: 'Biocon Ltd.',
        series: 'EQ',
        symbol: 'BIOCON',
        ISIN: 'INE376G01013',
      },
      {
        _id: '629ba41c0d8f441784cc76d4',
        name: 'CSB Bank Ltd.',
        series: 'EQ',
        symbol: 'CSBBANK',
        ISIN: 'INE679A01013',
      },
      {
        _id: '629ba41c0d8f441784cc76d5',
        name: 'Firstsource Solutions Ltd.',
        series: 'EQ',
        symbol: 'FSL',
        ISIN: 'INE684F01012',
      },
      {
        _id: '629ba41c0d8f441784cc76d6',
        name: 'Gujarat Pipavav Port Ltd.',
        series: 'EQ',
        symbol: 'GPPL',
        ISIN: 'INE517F01014',
      },
      {
        _id: '629ba41c0d8f441784cc76d7',
        name: 'Zydus Wellness Ltd.',
        series: 'EQ',
        symbol: 'ZYDUSWELL',
        ISIN: 'INE768C01010',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '629ba41c0d8f441784cc76d8',
        categoryId: {
          status: 'active',
          _id: 8,
          name: 'NIFTY Smallcap',
          description: 'NIFTY Smallcap',
        },
      },
    ],
    subCategories: [
      {
        _id: '629ba41c0d8f441784cc76d9',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '629ba41c0d8f441784cc76da',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
      {
        _id: '629ba41c0d8f441784cc76db',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '629ba41c0d8f441784cc76dc',
        subCategoryId: 5,
        subCategoryName: 'Thematics',
      },
      {
        _id: '629ba41c0d8f441784cc76dd',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '629ba41c0d8f441784cc76de',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '629ba41c0d8f441784cc76df',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '629ba41c0d8f441784cc76e0',
        functionalityId: {
          status: 'active',
          _id: 7,
          name: 'Covered',
          description: 'Covered',
        },
        functionalityName: 'Covered',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/the_hound.svg',
    tags: ['Bullish', 'Breakout'],
    startdate: '2022-06-04T02:54:40.972Z',
    _id: 20,
    IMAGELOGO: Hound,
    _idold: '629ba8e50d8f441784cc7727',
    name: 'The Hound',
    strategy: 'cheetah',
    description:
      "The Hound, Teaches us life is not about always great offence but defence. Hound's strategy is a master combination of vintage and new. While he drives the vintage ones to income acting as a hedge while focusing the rest on emerging opportunities",
    price: 100000,
    status: 'active',
    stocks: [
      {
        _id: '629ba8e50d8f441784cc7728',
        name: 'Hindalco Industries Ltd.',
        series: 'EQ',
        symbol: 'HINDALCO',
        ISIN: 'INE038A01020',
      },
      {
        _id: '629ba8e50d8f441784cc7729',
        name: 'Coal India Ltd.',
        series: 'EQ',
        symbol: 'COALINDIA',
        ISIN: 'INE522F01014',
      },
      {
        _id: '629ba8e50d8f441784cc772a',
        name: 'Cochin Shipyard Ltd.',
        series: 'EQ',
        symbol: 'COCHINSHIP',
        ISIN: 'INE704P01017',
      },
      {
        _id: '629ba8e50d8f441784cc772b',
        name: 'Kalpataru Power Transmission Ltd.',
        series: 'EQ',
        symbol: 'KALPATPOWR',
        ISIN: 'INE220B01022',
      },
      {
        _id: '629ba8e50d8f441784cc772c',
        name: 'Marico Ltd.',
        series: 'EQ',
        symbol: 'MARICO',
        ISIN: 'INE196A01026',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '629ba8e50d8f441784cc772d',
        categoryId: {
          status: 'active',
          _id: 8,
          name: 'NIFTY Smallcap',
          description: 'NIFTY Smallcap',
        },
      },
    ],
    subCategories: [
      {
        _id: '629ba8e50d8f441784cc772e',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '629ba8e50d8f441784cc772f',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
      {
        _id: '629ba8e50d8f441784cc7730',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '629ba8e50d8f441784cc7731',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '629ba8e50d8f441784cc7732',
        subCategoryId: 16,
        subCategoryName: 'Hedged Products',
      },
    ],
    functionality: [
      {
        _id: '629ba8e50d8f441784cc7733',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '629ba8e50d8f441784cc7734',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/poseidon.svg',
    tags: ['Bullish', 'Breakout'],
    startdate: '2022-06-03T05:32:05.236Z',
    _id: 16,
    IMAGELOGO: Poseidon,
    _idold: '629a4093ba3a0877d8a8c689',
    name: 'Poseidon',
    strategy: 'cheetah',
    description:
      "Poseidon as God of the sea, was an important Olympian power; he was the chief patron of Corinth, many cities of Magna Graecia, and also of Plato's legendary Atlantis. These great characteristics are deeply imbibed in the way the strategy functions. When the trend in favour, it essentially takes many investments along and once its time for the trend changes, its just exits and waits for another opportunity. ",
    price: 100000,
    status: 'active',
    stocks: [
      {
        _id: '629a4093ba3a0877d8a8c68a',
        name: 'ABB India Ltd.',
        series: 'EQ',
        symbol: 'ABB',
        ISIN: 'INE117A01022',
      },
      {
        _id: '629a4093ba3a0877d8a8c68b',
        name: 'BSE Ltd.',
        series: 'EQ',
        symbol: 'BSE',
        ISIN: 'INE118H01025',
      },
      {
        _id: '629a4093ba3a0877d8a8c68c',
        name: 'Apollo Tyres Ltd.',
        series: 'EQ',
        symbol: 'APOLLOTYRE',
        ISIN: 'INE438A01022',
      },
      {
        _id: '629a4093ba3a0877d8a8c68d',
        name: 'Bata India Ltd.',
        series: 'EQ',
        symbol: 'BATAINDIA',
        ISIN: 'INE176A01028',
      },
      {
        _id: '629a4093ba3a0877d8a8c68e',
        name: 'CESC Ltd.',
        series: 'EQ',
        symbol: 'CESC',
        ISIN: 'INE486A01021',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '629a4093ba3a0877d8a8c68f',
        categoryId: {
          status: 'active',
          _id: 5,
          name: 'Nifty 100',
          description: 'Nifty 100',
        },
      },
    ],
    subCategories: [
      {
        _id: '629a4093ba3a0877d8a8c690',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
      {
        _id: '629a4093ba3a0877d8a8c691',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '629a4093ba3a0877d8a8c692',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '629a4093ba3a0877d8a8c693',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '629a4093ba3a0877d8a8c694',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '629a4093ba3a0877d8a8c695',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '629a4093ba3a0877d8a8c696',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
      {
        _id: '629a4093ba3a0877d8a8c697',
        functionalityId: {
          status: 'active',
          _id: 5,
          name: 'Hedged',
          description: 'Hedged',
        },
        functionalityName: 'Hedged',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/marko_polo.svg',
    tags: ['Bullish', 'Breakout'],
    startdate: '2022-06-02T04:37:19.331Z',
    _id: 14,
    IMAGELOGO: MarcoPolo,
    _idold: '6298cbb94c22b025476fdfaf',
    name: 'Marco Polo',
    strategy: 'cheetah',
    description:
      'Marco Polo is known for travelling along the Silk Road to China, where he explored and documented much of Asia not yet explored by Europeans. These strong characteristics and traits form the very basis of the strategy. He is constantly on the lookout for opportunities arising the next big companies of the Indian Stock Market',
    price: 5000,
    status: 'active',
    stocks: [
      {
        _id: '6298cbb94c22b025476fdfb0',
        name: 'Berger Paints India Ltd.',
        series: 'EQ',
        symbol: 'BERGEPAINT',
        ISIN: 'INE463A01038',
      },
      {
        _id: '6298cbb94c22b025476fdfb1',
        name: 'Grasim Industries Ltd.',
        series: 'EQ',
        symbol: 'GRASIM',
        ISIN: 'INE047A01021',
      },
      {
        _id: '6298cbb94c22b025476fdfb2',
        name: 'Power Grid Corporation of India Ltd.',
        series: 'EQ',
        symbol: 'POWERGRID',
        ISIN: 'INE752E01010',
      },
      {
        _id: '6298cbb94c22b025476fdfb3',
        name: 'Tata Consumer Products Ltd.',
        series: 'EQ',
        symbol: 'TATACONSUM',
        ISIN: 'INE192A01025',
      },
      {
        _id: '6298cbb94c22b025476fdfb4',
        name: 'Relaxo Footwears Ltd.',
        series: 'EQ',
        symbol: 'RELAXO',
        ISIN: 'INE131B01039',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6298cbb94c22b025476fdfb5',
        categoryId: {
          status: 'active',
          _id: 5,
          name: 'Nifty 100',
          description: 'Nifty 100',
        },
      },
    ],
    subCategories: [
      {
        _id: '6298cbb94c22b025476fdfb6',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '6298cbb94c22b025476fdfb7',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '6298cbb94c22b025476fdfb8',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '6298cbb94c22b025476fdfb9',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
    ],
    functionality: [
      {
        _id: '6298cbb94c22b025476fdfba',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '6298cbb94c22b025476fdfbb',
        functionalityId: {
          status: 'active',
          _id: 7,
          name: 'Covered',
          description: 'Covered',
        },
        functionalityName: 'Covered',
      },
    ],
    trading_frequency: 'quaterly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/vasco_da_gama.svg',
    tags: ['Bullish', 'Breakout', 'Arbitrage'],
    startdate: '2022-06-02T04:37:19.331Z',
    _id: 13,
    IMAGELOGO: VascodaGama,
    _idold: '6298c9984c22b025476fdf7a',
    name: 'Vasco-da-Gama',
    strategy: 'cheetah',
    description:
      'Vasco da Gama is a great explorer who set his journey into the unchartered waters and found a golden route to India. These great characteristics are deeply imbibed into thesis on which this strategy is built.\nConstantly on a look out for the best performing stock to deploy investments and steer you towards a profitable journey\n',
    price: 100000,
    status: 'active',
    stocks: [
      {
        _id: '6298c9984c22b025476fdf7b',
        name: 'ABB India Ltd.',
        series: 'EQ',
        symbol: 'ABB',
        ISIN: 'INE117A01022',
      },
      {
        _id: '6298c9984c22b025476fdf7c',
        name: 'Abbott India Ltd.',
        series: 'EQ',
        symbol: 'ABBOTINDIA',
        ISIN: 'INE358A01014',
      },
      {
        _id: '6298c9984c22b025476fdf7d',
        name: 'Zydus Wellness Ltd.',
        series: 'EQ',
        symbol: 'ZYDUSWELL',
        ISIN: 'INE768C01010',
      },
      {
        _id: '6298c9984c22b025476fdf7e',
        name: 'Marico Ltd.',
        series: 'EQ',
        symbol: 'MARICO',
        ISIN: 'INE196A01026',
      },
      {
        _id: '6298c9984c22b025476fdf7f',
        name: 'HCL Technologies Ltd.',
        series: 'EQ',
        symbol: 'HCLTECH',
        ISIN: 'INE860A01027',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6298c9984c22b025476fdf80',
        categoryId: {
          status: 'active',
          _id: 5,
          name: 'Nifty 100',
          description: 'Nifty 100',
        },
      },
    ],
    subCategories: [
      {
        _id: '6298c9984c22b025476fdf81',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '6298c9984c22b025476fdf82',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
      {
        _id: '6298c9984c22b025476fdf83',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '6298c9984c22b025476fdf84',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
    ],
    functionality: [
      {
        _id: '6298c9984c22b025476fdf85',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '6298c9984c22b025476fdf86',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/wizard.svg',
    tags: ['Bullish', 'Breakout'],
    startdate: '2022-06-02T04:37:19.331Z',
    _id: 15,
    IMAGELOGO: Columbus,
    _idold: '6298d0cb4c22b025476fdfe0',
    name: 'Columbus',
    strategy: 'cheetah',
    description:
      'Christopher Columbus, The great explorer credited with discovering the new world. His famous voyages led to the formation of great nations. His never dying passion is deeply inculcated in the thesis in which the strategy is built, covers the next multi-baggers, keeps an eye on the emerging opportunities and tactically deploys capital. ',
    price: 100000,
    status: 'active',
    stocks: [
      {
        _id: '6298d0cb4c22b025476fdfe1',
        name: 'Hindalco Industries Ltd.',
        series: 'EQ',
        symbol: 'HINDALCO',
        ISIN: 'INE038A01020',
      },
      {
        _id: '6298d0cb4c22b025476fdfe2',
        name: 'Voltas Ltd.',
        series: 'EQ',
        symbol: 'VOLTAS',
        ISIN: 'INE226A01021',
      },
      {
        _id: '6298d0cb4c22b025476fdfe3',
        name: 'Dr. Lal Path Labs Ltd.',
        series: 'EQ',
        symbol: 'LALPATHLAB',
        ISIN: 'INE600L01024',
      },
      {
        _id: '6298d0cb4c22b025476fdfe4',
        name: 'GAIL (India) Ltd.',
        series: 'EQ',
        symbol: 'GAIL',
        ISIN: 'INE129A01019',
      },
      {
        _id: '6298d0cb4c22b025476fdfe5',
        name: 'Indian Railway Catering And Tourism Corporation Ltd.',
        series: 'EQ',
        symbol: 'IRCTC',
        ISIN: 'INE335Y01020',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6298d0cb4c22b025476fdfe6',
        categoryId: {
          status: 'active',
          _id: 5,
          name: 'Nifty 100',
          description: 'Nifty 100',
        },
      },
    ],
    subCategories: [
      {
        _id: '6298d0cb4c22b025476fdfe7',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '6298d0cb4c22b025476fdfe8',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '6298d0cb4c22b025476fdfe9',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '6298d0cb4c22b025476fdfea',
        subCategoryId: 14,
        subCategoryName: 'Arbitrage',
      },
      {
        _id: '6298d0cb4c22b025476fdfeb',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '6298d0cb4c22b025476fdfec',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '6298d0cb4c22b025476fdfed',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/priam.svg',
    tags: ['Bullish', 'Arbitrage'],
    startdate: '2022-05-30T02:51:25.859Z',
    _id: 12,
    IMAGELOGO: ZeusGreat,
    _idold: '629651e692395d661ca99a60',
    name: 'Zeus - The Great!',
    strategy: 'cheetah',
    description:
      "Meet Zeus. He hates losing money as much as a Gorgon hates Percy Jackson. He belongs in the pantheon of greats such as Odysseus, Hercules and Achilles.  Whether he's leading the Greek gods in battle or striking terror into the hearts of mortals, Zeus is a sight to behold!\n\nHe works to improve your results and make it easy for you to participate in short term investing opportunities of the best blue-chip stocks. That's why he's equipped with the best tech on the market to make your investment play more exciting and safer than ever before and helps you get ahead of the pack.",
    price: 1000,
    status: 'active',
    stocks: [
      {
        _id: '629651e692395d661ca99a61',
        name: 'Ashok Leyland Ltd.',
        series: 'EQ',
        symbol: 'ASHOKLEY',
        ISIN: 'INE208A01029',
      },
      {
        _id: '629651e692395d661ca99a62',
        name: 'TV18 Broadcast Ltd.',
        series: 'EQ',
        symbol: 'TV18BRDCST',
        ISIN: 'INE886H01027',
      },
      {
        _id: '629651e692395d661ca99a63',
        name: 'Suzlon Energy Ltd.',
        series: 'EQ',
        symbol: 'SUZLON',
        ISIN: 'INE040H01021',
      },
      {
        _id: '629651e692395d661ca99a64',
        name: 'Indian Bank',
        series: 'EQ',
        symbol: 'INDIANB',
        ISIN: 'INE562A01011',
      },
      {
        _id: '629651e692395d661ca99a65',
        name: 'Indian Oil Corporation Ltd.',
        series: 'EQ',
        symbol: 'IOC',
        ISIN: 'INE242A01010',
      },
      {
        _id: '629651e692395d661ca99a66',
        name: 'Zomato Ltd.',
        series: 'EQ',
        symbol: 'ZOMATO',
        ISIN: 'INE758T01015',
      },
      {
        _id: '629651e692395d661ca99a67',
        name: 'Bank of Baroda',
        series: 'EQ',
        symbol: 'BANKBARODA',
        ISIN: 'INE028A01039',
      },
      {
        _id: '629651e692395d661ca99a68',
        name: 'Infibeam Avenues Ltd.',
        series: 'EQ',
        symbol: 'INFIBEAM',
        ISIN: 'INE483S01020',
      },
      {
        _id: '629651e692395d661ca99a69',
        name: 'Gujarat Pipavav Port Ltd.',
        series: 'EQ',
        symbol: 'GPPL',
        ISIN: 'INE517F01014',
      },
      {
        _id: '629651e692395d661ca99a6a',
        name: 'IDFC First Bank Ltd.',
        series: 'EQ',
        symbol: 'IDFCFIRSTB',
        ISIN: 'INE092T01019',
      },
    ],
    risk: 'medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '629651e692395d661ca99a6b',
        categoryId: {
          status: 'active',
          _id: 3,
          name: 'NIFTY Midcap 100',
          description: 'NIFTY Midcap 100',
        },
      },
    ],
    subCategories: [
      {
        _id: '629651e692395d661ca99a6c',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '629651e692395d661ca99a6d',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '629651e692395d661ca99a6e',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '629651e692395d661ca99a6f',
        subCategoryId: 5,
        subCategoryName: 'Thematics',
      },
      {
        _id: '629651e692395d661ca99a70',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '629651e692395d661ca99a71',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '629651e692395d661ca99a72',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
      {
        _id: '629651e692395d661ca99a73',
        functionalityId: {
          status: 'active',
          _id: 3,
          name: 'Event Based',
          description: 'Event Based',
        },
        functionalityName: 'Event Based',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/xerxes.svg',
    tags: ['Arbitrage', 'See More', 'Bullish'],
    startdate: '2022-05-30T02:51:25.859Z',
    _id: 10,
    IMAGELOGO: Xerxes,
    _idold: '6296325f92395d661ca99863',
    name: 'Xerxes',
    strategy: 'cheetah',
    description:
      'Xerxes. He is a Savage He knows that timing is everything in the stock market, His investing strategy is pure genius! He’ll wait for the best time to invest, and he’s always ready to inspire some serious investment and he’ll invest in the best opportunities in Bank Nifty',
    price: 250000,
    status: 'active',
    stocks: [
      {
        _id: '6296325f92395d661ca99864',
        name: 'AU Small Finance Bank Ltd.',
        series: 'EQ',
        symbol: 'AUBANK',
        ISIN: 'INE949L01017',
      },
      {
        _id: '6296325f92395d661ca99865',
        name: 'Bank of India',
        series: 'EQ',
        symbol: 'BANKINDIA',
        ISIN: 'INE084A01016',
      },
    ],
    risk: 'High',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6296325f92395d661ca99866',
        categoryId: {
          status: 'active',
          _id: 2,
          name: 'NIFTY BANK',
          description: 'Nifty BANk',
        },
      },
    ],
    subCategories: [
      {
        _id: '6296325f92395d661ca99867',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
      {
        _id: '6296325f92395d661ca99868',
        subCategoryId: 16,
        subCategoryName: 'Hedged Products',
      },
      {
        _id: '6296325f92395d661ca99869',
        subCategoryId: 11,
        subCategoryName: 'Continous Futures',
      },
    ],
    functionality: [
      {
        _id: '6296325f92395d661ca9986a',
        functionalityId: {
          status: 'active',
          _id: 2,
          name: 'Long & Short',
          description: 'Long & Short',
        },
        functionalityName: 'Long & Short',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/aristotle.svg',
    tags: ['Bullish', 'Breakout'],
    startdate: '2022-05-30T02:51:25.859Z',
    _id: 9,
    IMAGELOGO: Aristotle,
    _idold: '6296308e92395d661ca99839',
    name: 'Aristotle',
    strategy: 'cheetah',
    description:
      'Aristotle. A great philosopher.  He knows that timing is everything in the stock market, His investing strategy is pure genius! He’ll wait for the best time to invest, and he’s always ready to inspire some serious investment and he’ll invest in the best opportunities in emerging mid-cap stocks.',
    price: 50000,
    status: 'active',
    stocks: [
      {
        _id: '6296308e92395d661ca9983a',
        name: 'Jubilant Foodworks Ltd.',
        series: 'EQ',
        symbol: 'JUBLFOOD',
        ISIN: 'INE797F01020',
      },
      {
        _id: '6296308e92395d661ca9983b',
        name: 'BSE Ltd.',
        series: 'EQ',
        symbol: 'BSE',
        ISIN: 'INE118H01025',
      },
      {
        _id: '6296308e92395d661ca9983c',
        name: 'PVR Ltd.',
        series: 'EQ',
        symbol: 'PVR',
        ISIN: 'INE191H01014',
      },
      {
        _id: '6296308e92395d661ca9983d',
        name: 'Deepak Nitrite Ltd.',
        series: 'EQ',
        symbol: 'DEEPAKNTR',
        ISIN: 'INE288B01029',
      },
      {
        _id: '6296308e92395d661ca9983e',
        name: 'Exide Industries Ltd.',
        series: 'EQ',
        symbol: 'EXIDEIND',
        ISIN: 'INE302A01020',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6296308e92395d661ca9983f',
        categoryId: {
          status: 'active',
          _id: 3,
          name: 'NIFTY Midcap 100',
          description: 'NIFTY Midcap 100',
        },
      },
    ],
    subCategories: [
      {
        _id: '6296308e92395d661ca99840',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '6296308e92395d661ca99841',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '6296308e92395d661ca99842',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '6296308e92395d661ca99843',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/socrates.svg',
    tags: ['Bullish', 'Breakout', 'Arbitrage'],
    startdate: '2022-05-30T02:51:25.859Z',
    _id: 8,
    IMAGELOGO: Archimedes,
    _idold: '6296289f92395d661ca997f5',
    name: 'Archimedes',
    strategy: 'cheetah',
    description:
      'Archimedes, A great mathematician. He knows that timing is everything in the stock market, His investing strategy is pure genius! He’ll wait for the best time to invest, and he’s always ready to inspire some serious investment and he’ll invest in the nations biggest banks when they’re going up in value.',
    price: 50000,
    status: 'active',
    stocks: [
      {
        _id: '6296289f92395d661ca997f6',
        name: 'Canara Bank',
        series: 'EQ',
        symbol: 'CANBK',
        ISIN: 'INE476A01014',
      },
      {
        _id: '6296289f92395d661ca997f7',
        name: 'UCO Bank',
        series: 'EQ',
        symbol: 'UCOBANK',
        ISIN: 'INE691A01018',
      },
      {
        _id: '6296289f92395d661ca997f8',
        name: 'Federal Bank Ltd.',
        series: 'EQ',
        symbol: 'FEDERALBNK',
        ISIN: 'INE171A01029',
      },
      {
        _id: '6296289f92395d661ca997f9',
        name: 'Punjab National Bank',
        series: 'EQ',
        symbol: 'PNB',
        ISIN: 'INE160A01022',
      },
      {
        _id: '6296289f92395d661ca997fa',
        name: 'RBL Bank Ltd.',
        series: 'EQ',
        symbol: 'RBLBANK',
        ISIN: 'INE976G01028',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6296289f92395d661ca997fb',
        categoryId: {
          status: 'active',
          _id: 2,
          name: 'NIFTY BANK',
          description: 'Nifty BANk',
        },
      },
    ],
    subCategories: [
      {
        _id: '6296289f92395d661ca997fc',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '6296289f92395d661ca997fd',
        subCategoryId: 5,
        subCategoryName: 'Thematics',
      },
      {
        _id: '6296289f92395d661ca997fe',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '6296289f92395d661ca997ff',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '6296289f92395d661ca99800',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '6296289f92395d661ca99801',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '6296289f92395d661ca99802',
        functionalityId: {
          status: 'active',
          _id: 4,
          name: 'Arbitrage',
          description: 'Arbitrage',
        },
        functionalityName: 'Arbitrage',
      },
      {
        _id: '6296289f92395d661ca99803',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/matador.svg',
    tags: ['Bearish', 'Bullish'],
    startdate: '2022-05-30T02:51:25.859Z',
    _id: 11,
    IMAGELOGO: Matador,
    _idold: '6296353f92395d661ca998cd',
    name: 'Matador',
    strategy: 'cheetah',
    description:
      'Matador. When in action, what sight to watch. He knows that timing is everything in the stock market, His investing strategy is pure genius! He will trade in bank nifty futures on a long and short basis generating superior alpha',
    price: 200000,
    status: 'active',
    stocks: [
      {
        _id: '6296353f92395d661ca998ce',
        name: 'HDFC Bank Ltd.',
        series: 'EQ',
        symbol: 'HDFCBANK',
        ISIN: 'INE040A01034',
      },
    ],
    risk: 'High',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6296353f92395d661ca998cf',
        categoryId: {
          status: 'active',
          _id: 2,
          name: 'NIFTY BANK',
          description: 'Nifty BANk',
        },
      },
    ],
    subCategories: [
      {
        _id: '6296353f92395d661ca998d0',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
      {
        _id: '6296353f92395d661ca998d1',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '6296353f92395d661ca998d2',
        subCategoryId: 11,
        subCategoryName: 'Continous Futures',
      },
      {
        _id: '6296353f92395d661ca998d3',
        subCategoryId: 12,
        subCategoryName: 'Fixed Income',
      },
      {
        _id: '6296353f92395d661ca998d4',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '6296353f92395d661ca998d5',
        functionalityId: {
          status: 'active',
          _id: 7,
          name: 'Covered',
          description: 'Covered',
        },
        functionalityName: 'Covered',
      },
      {
        _id: '6296353f92395d661ca998d6',
        functionalityId: {
          status: 'active',
          _id: 2,
          name: 'Long & Short',
          description: 'Long & Short',
        },
        functionalityName: 'Long & Short',
      },
      {
        _id: '6296353f92395d661ca998d7',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/hera.svg',
    tags: ['Arbitrage', 'Bullish', 'Breakout'],
    startdate: '2022-05-30T02:46:18.844Z',
    _id: 7,
    IMAGELOGO: Hera,
    _idold: '6294ce03a9100b7a001fd643',
    name: 'Hera',
    strategy: 'cheetah',
    description:
      "Hera, is a powerful greek goddess known for her role as the head of the Olympus and for her wisdom. She's a legend!\n\n She will focus on a few true mid cap opportunities, return your original investment as quickly as possible, then enjoy a comfortable cash flow of dividends.",
    price: 50000,
    status: 'active',
    stocks: [
      {
        _id: '6294ce03a9100b7a001fd644',
        name: 'Asahi India Glass Ltd.',
        series: 'EQ',
        symbol: 'ASAHIINDIA',
        ISIN: 'INE439A01020',
      },
      {
        _id: '6294ce03a9100b7a001fd645',
        name: 'Berger Paints India Ltd.',
        series: 'EQ',
        symbol: 'BERGEPAINT',
        ISIN: 'INE463A01038',
      },
      {
        _id: '6294ce03a9100b7a001fd646',
        name: 'CRISIL Ltd.',
        series: 'EQ',
        symbol: 'CRISIL',
        ISIN: 'INE007A01025',
      },
      {
        _id: '6294ce03a9100b7a001fd647',
        name: 'Dr. Lal Path Labs Ltd.',
        series: 'EQ',
        symbol: 'LALPATHLAB',
        ISIN: 'INE600L01024',
      },
      {
        _id: '6294ce03a9100b7a001fd648',
        name: 'GAIL (India) Ltd.',
        series: 'EQ',
        symbol: 'GAIL',
        ISIN: 'INE129A01019',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6294ce03a9100b7a001fd649',
        categoryId: {
          status: 'active',
          _id: 3,
          name: 'NIFTY Midcap 100',
          description: 'NIFTY Midcap 100',
        },
      },
    ],
    subCategories: [
      {
        _id: '6294ce03a9100b7a001fd64a',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
      {
        _id: '6294ce03a9100b7a001fd64b',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '6294ce03a9100b7a001fd64c',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '6294ce03a9100b7a001fd64d',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '6294ce03a9100b7a001fd64e',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '6294ce03a9100b7a001fd64f',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '6294ce03a9100b7a001fd650',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
      {
        _id: '6294ce03a9100b7a001fd651',
        functionalityId: {
          status: 'active',
          _id: 4,
          name: 'Arbitrage',
          description: 'Arbitrage',
        },
        functionalityName: 'Arbitrage',
      },
      {
        _id: '6294ce03a9100b7a001fd652',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/pythagoras.svg',
    tags: ['Bullish', 'Breakout', 'Arbitrage'],
    startdate: '2022-05-30T02:46:18.844Z',
    _id: 5,
    IMAGELOGO: Pythagoras,
    _idold: '629471f4a9100b7a001fd48e',
    name: 'Pythagoras',
    strategy: 'cheetah',
    description:
      'Pythagoras, a man who invented the theory of everything, is also a great mathematician. He knows that timing is everything in the stock market, His investing strategy is pure genius! He’ll wait for the best time to invest, and he’s always ready to inspire some serious investment and he’ll invest in the nations biggest banks when they’re going up in value. ',
    price: 50000,
    status: 'active',
    stocks: [
      {
        _id: '629471f4a9100b7a001fd48f',
        name: 'IndusInd Bank Ltd.',
        series: 'EQ',
        symbol: 'INDUSINDBK',
        ISIN: 'INE095A01012',
      },
      {
        _id: '629471f4a9100b7a001fd490',
        name: 'ICICI Bank Ltd.',
        series: 'EQ',
        symbol: 'ICICIBANK',
        ISIN: 'INE090A01021',
      },
      {
        _id: '629471f4a9100b7a001fd491',
        name: 'Kotak Mahindra Bank Ltd.',
        series: 'EQ',
        symbol: 'KOTAKBANK',
        ISIN: 'INE237A01028',
      },
      {
        _id: '629471f4a9100b7a001fd492',
        name: 'HDFC Bank Ltd.',
        series: 'EQ',
        symbol: 'HDFCBANK',
        ISIN: 'INE040A01034',
      },
      {
        _id: '629471f4a9100b7a001fd493',
        name: 'State Bank of India',
        series: 'EQ',
        symbol: 'SBIN',
        ISIN: 'INE062A01020',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '629471f4a9100b7a001fd494',
        categoryId: {
          status: 'active',
          _id: 2,
          name: 'NIFTY BANK',
          description: 'Nifty BANk',
        },
      },
    ],
    subCategories: [
      {
        _id: '629471f4a9100b7a001fd495',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
      {
        _id: '629471f4a9100b7a001fd496',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
      {
        _id: '629471f4a9100b7a001fd497',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '629471f4a9100b7a001fd498',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '629471f4a9100b7a001fd499',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
    ],
    functionality: [
      {
        _id: '629471f4a9100b7a001fd49a',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/athena.svg',
    tags: ['Bullish', 'Breakout', 'Arbitrage'],
    startdate: '2022-05-30T02:46:18.844Z',
    _id: 6,
    IMAGELOGO: Athena,
    _idold: '6294c9b5a9100b7a001fd60b',
    name: 'Athena',
    strategy: 'cheetah',
    description:
      " Athena, the Ancient Greek Goddess of wisdom, courage and inspiration. She is not only powerful but fearless in her pursuit of excellence. We think it's an appropriate namesake for our middle market investment approach that leverages our proprietary tech to find the best opportunities in emerging mid cap stocks.",
    price: 50000,
    status: 'active',
    stocks: [
      {
        _id: '6294c9b5a9100b7a001fd60c',
        name: 'ABB India Ltd.',
        series: 'EQ',
        symbol: 'ABB',
        ISIN: 'INE117A01022',
      },
      {
        _id: '6294c9b5a9100b7a001fd60d',
        name: 'Astral Ltd.',
        series: 'EQ',
        symbol: 'ASTRAL',
        ISIN: 'INE006I01046',
      },
      {
        _id: '6294c9b5a9100b7a001fd60e',
        name: 'Dabur India Ltd.',
        series: 'EQ',
        symbol: 'DABUR',
        ISIN: 'INE016A01026',
      },
      {
        _id: '6294c9b5a9100b7a001fd60f',
        name: 'Escorts Ltd.',
        series: 'EQ',
        symbol: 'ESCORTS',
        ISIN: 'INE042A01014',
      },
      {
        _id: '6294c9b5a9100b7a001fd610',
        name: 'Fortis Healthcare Ltd.',
        series: 'EQ',
        symbol: 'FORTIS',
        ISIN: 'INE061F01013',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6294c9b5a9100b7a001fd611',
        categoryId: {
          status: 'active',
          _id: 3,
          name: 'NIFTY Midcap 100',
          description: 'NIFTY Midcap 100',
        },
      },
    ],
    subCategories: [
      {
        _id: '6294c9b5a9100b7a001fd612',
        subCategoryId: 1,
        subCategoryName: 'Asset Allocation',
      },
      {
        _id: '6294c9b5a9100b7a001fd613',
        subCategoryId: 2,
        subCategoryName: 'Dividend Income',
      },
      {
        _id: '6294c9b5a9100b7a001fd614',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '6294c9b5a9100b7a001fd615',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '6294c9b5a9100b7a001fd616',
        subCategoryId: 6,
        subCategoryName: 'Value',
      },
      {
        _id: '6294c9b5a9100b7a001fd617',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '6294c9b5a9100b7a001fd618',
        functionalityId: {
          status: 'active',
          _id: 8,
          name: 'Income',
          description: 'Income',
        },
        functionalityName: 'Income',
      },
      {
        _id: '6294c9b5a9100b7a001fd619',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/achilles.svg',
    tags: ['Bullish', 'Breakout', 'Arbitrage'],
    startdate: '2022-05-28T06:44:21.588Z',
    _id: 2,
    IMAGELOGO: Achilles,
    _idold: '62923d421d9be03df7a4a5f9',
    name: 'Achilles',
    strategy: 'cheetah',
    description:
      "Meet Achilles. He belongs in the pantheon of greats such as Odysseus, Hercules and Zeus. Whether he's leading the Greek gods in battle or striking terror into the hearts of mortals, Achilles is a sight to behold!\n\nHe works to improve your results and make it easy for you to participate in short term investing opportunities of the best blue-chip stocks. That's why he's equipped with the best tech on the market to make your investment play more exciting and safer than ever before and helps you get ahead of the pack.",
    price: 10000,
    status: 'active',
    stocks: [
      {
        _id: '62923d421d9be03df7a4a5fa',
        name: 'Bajaj Auto Ltd.',
        series: 'EQ',
        symbol: 'BAJAJ-AUTO',
        ISIN: 'INE917I01010',
      },
      {
        _id: '62923d421d9be03df7a4a5fb',
        name: 'Bharat Petroleum Corporation Ltd.',
        series: 'EQ',
        symbol: 'BPCL',
        ISIN: 'INE029A01011',
      },
      {
        _id: '62923d421d9be03df7a4a5fc',
        name: 'Bharti Airtel Ltd.',
        series: 'EQ',
        symbol: 'BHARTIARTL',
        ISIN: 'INE397D01024',
      },
      {
        _id: '62923d421d9be03df7a4a5fd',
        name: 'Ceat Ltd.',
        series: 'EQ',
        symbol: 'CEATLTD',
        ISIN: 'INE482A01020',
      },
      {
        _id: '62923d421d9be03df7a4a5fe',
        name: 'Coal India Ltd.',
        series: 'EQ',
        symbol: 'COALINDIA',
        ISIN: 'INE522F01014',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '62923d421d9be03df7a4a5ff',
        categoryId: {
          status: 'active',
          _id: 1,
          name: 'NIFTY 50',
          description: 'Nifty 50',
        },
      },
    ],
    subCategories: [
      {
        _id: '62923d421d9be03df7a4a600',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '62923d421d9be03df7a4a601',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '62923d421d9be03df7a4a602',
        subCategoryId: 8,
        subCategoryName: 'Bluechips',
      },
      {
        _id: '62923d421d9be03df7a4a603',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
      {
        _id: '62923d421d9be03df7a4a604',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
    ],
    functionality: [
      {
        _id: '62923d421d9be03df7a4a605',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/hector.svg',
    tags: ['Bullish', 'Breakout', 'Arbitrage'],
    startdate: '2022-05-28T06:44:21.588Z',
    _id: 3,
    IMAGELOGO: Odysseus,
    _idold: '62924c041d9be03df7a4a70d',
    name: 'Odysseus',
    strategy: 'cheetah',
    description:
      "Meet Odysseus. He belongs in the pantheon of greats such as Achilles, Hercules and Zeus. Whether he's leading the Greek gods in battle or striking terror into the hearts of mortals, Odysseus is a sight to behold!\n\nHe works to improve your results and make it easy for you to participate in short term investing opportunities of the best blue-chip stocks. That's why he's equipped with the best tech on the market to make your investment play more exciting and safer than ever before and helps you get ahead of the pack.",
    price: 50000,
    status: 'active',
    stocks: [
      {
        _id: '62924c041d9be03df7a4a70e',
        name: 'Cipla Ltd.',
        series: 'EQ',
        symbol: 'CIPLA',
        ISIN: 'INE059A01026',
      },
      {
        _id: '62924c041d9be03df7a4a70f',
        name: 'Coal India Ltd.',
        series: 'EQ',
        symbol: 'COALINDIA',
        ISIN: 'INE522F01014',
      },
      {
        _id: '62924c041d9be03df7a4a710',
        name: 'HDFC Bank Ltd.',
        series: 'EQ',
        symbol: 'HDFCBANK',
        ISIN: 'INE040A01034',
      },
      {
        _id: '62924c041d9be03df7a4a711',
        name: 'ICICI Bank Ltd.',
        series: 'EQ',
        symbol: 'ICICIBANK',
        ISIN: 'INE090A01021',
      },
      {
        _id: '62924c041d9be03df7a4a712',
        name: 'Infosys Ltd.',
        series: 'EQ',
        symbol: 'INFY',
        ISIN: 'INE009A01021',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '62924c041d9be03df7a4a713',
        categoryId: {
          status: 'active',
          _id: 1,
          name: 'NIFTY 50',
          description: 'Nifty 50',
        },
      },
    ],
    subCategories: [
      {
        _id: '62924c041d9be03df7a4a714',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '62924c041d9be03df7a4a715',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '62924c041d9be03df7a4a716',
        subCategoryId: 5,
        subCategoryName: 'Thematics',
      },
      {
        _id: '62924c041d9be03df7a4a717',
        subCategoryId: 8,
        subCategoryName: 'Bluechips',
      },
      {
        _id: '62924c041d9be03df7a4a718',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
    ],
    functionality: [
      {
        _id: '62924c041d9be03df7a4a719',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/ares.svg',
    tags: ['Bullish', 'Arbitrage', 'Breakout'],
    startdate: '2022-05-28T06:44:21.588Z',
    _id: 1,
    IMAGELOGO: Zeus1,
    _idold: '6292394a1d9be03df7a4a553',
    name: 'Zeus',
    strategy: 'cheetah',
    description:
      "Meet Zeus. He hates losing money as much as a Gorgon hates Percy Jackson. He belongs in the pantheon of greats such as Odysseus, Hercules and Achilles.  Whether he's leading the Greek gods in battle or striking terror into the hearts of mortals, Zeus is a sight to behold.\n\nHe works to improve your results and make it easy for you to participate in short term investing opportunities of the best blue-chip stocks. That's why he's equipped with the best tech on the market to make your investment play more exciting and safer than ever before and helps you get ahead of the pack.",
    price: 50000,
    status: 'active',
    stocks: [
      {
        _id: '6292394a1d9be03df7a4a554',
        name: 'Tata Steel Ltd.',
        series: 'EQ',
        symbol: 'TATASTEEL',
        ISIN: 'INE081A01012',
      },
      {
        _id: '6292394a1d9be03df7a4a555',
        name: 'ACC Ltd.',
        series: 'EQ',
        symbol: 'ACC',
        ISIN: 'INE012A01025',
      },
      {
        _id: '6292394a1d9be03df7a4a556',
        name: 'Hindalco Industries Ltd.',
        series: 'EQ',
        symbol: 'HINDALCO',
        ISIN: 'INE038A01020',
      },
      {
        _id: '6292394a1d9be03df7a4a557',
        name: 'Wipro Ltd.',
        series: 'EQ',
        symbol: 'WIPRO',
        ISIN: 'INE075A01022',
      },
      {
        _id: '6292394a1d9be03df7a4a558',
        name: 'Oil & Natural Gas Corporation Ltd.',
        series: 'EQ',
        symbol: 'ONGC',
        ISIN: 'INE213A01029',
      },
    ],
    risk: 'Medium',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '6292394a1d9be03df7a4a559',
        categoryId: {
          status: 'active',
          _id: 1,
          name: 'NIFTY 50',
          description: 'Nifty 50',
        },
      },
    ],
    subCategories: [
      {
        _id: '6292394a1d9be03df7a4a55a',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '6292394a1d9be03df7a4a55b',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '6292394a1d9be03df7a4a55c',
        subCategoryId: 8,
        subCategoryName: 'Bluechips',
      },
      {
        _id: '6292394a1d9be03df7a4a55d',
        subCategoryId: 15,
        subCategoryName: 'Trend Following',
      },
    ],
    functionality: [
      {
        _id: '6292394a1d9be03df7a4a55e',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
      {
        _id: '6292394a1d9be03df7a4a55f',
        functionalityId: {
          status: 'active',
          _id: 4,
          name: 'Arbitrage',
          description: 'Arbitrage',
        },
        functionalityName: 'Arbitrage',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
  {
    imgUrl: '/static/images/quants/hercules.svg',
    tags: ['Bullish', 'Breakout', 'Arbitrage'],
    startdate: '2022-05-28T06:44:21.588Z',
    _id: 4,
    IMAGELOGO: Hercules,
    _idold: '62924d4d1d9be03df7a4a73c',
    name: 'Hercules',
    strategy: 'cheetah',
    description:
      "Meet Hercules. He belongs in the pantheon of greats such as Achilles, Odysseus and Zeus. Whether he's leading the Greek gods in battle or striking terror into the hearts of mortals, Hercules is a sight to behold!\n\nHe works to improve your results and make it easy for you to participate in short term investing opportunities of the best blue-chip stocks. That's why he's equipped with the best tech on the market to make your investment play more exciting and safer than ever before and helps you get ahead of the pack.",
    price: 50000,
    status: 'active',
    stocks: [
      {
        _id: '62924d4d1d9be03df7a4a73d',
        name: 'Vedanta Ltd.',
        series: 'EQ',
        symbol: 'VEDL',
        ISIN: 'INE205A01025',
      },
      {
        _id: '62924d4d1d9be03df7a4a73e',
        name: 'UltraTech Cement Ltd.',
        series: 'EQ',
        symbol: 'ULTRACEMCO',
        ISIN: 'INE481G01011',
      },
      {
        _id: '62924d4d1d9be03df7a4a73f',
        name: 'Titan Company Ltd.',
        series: 'EQ',
        symbol: 'TITAN',
        ISIN: 'INE280A01028',
      },
      {
        _id: '62924d4d1d9be03df7a4a740',
        name: 'Tata Motors Ltd.',
        series: 'EQ',
        symbol: 'TATAMOTORS',
        ISIN: 'INE155A01022',
      },
      {
        _id: '62924d4d1d9be03df7a4a741',
        name: 'State Bank of India',
        series: 'EQ',
        symbol: 'SBIN',
        ISIN: 'INE062A01020',
      },
    ],
    risk: 'Low',
    createdBy: 'MF_Admin',
    categories: [
      {
        _id: '62924d4d1d9be03df7a4a742',
        categoryId: {
          status: 'active',
          _id: 1,
          name: 'NIFTY 50',
          description: 'Nifty 50',
        },
      },
    ],
    subCategories: [
      {
        _id: '62924d4d1d9be03df7a4a743',
        subCategoryId: 3,
        subCategoryName: 'Growth',
      },
      {
        _id: '62924d4d1d9be03df7a4a744',
        subCategoryId: 4,
        subCategoryName: 'Momentum',
      },
      {
        _id: '62924d4d1d9be03df7a4a745',
        subCategoryId: 5,
        subCategoryName: 'Thematics',
      },
      {
        _id: '62924d4d1d9be03df7a4a746',
        subCategoryId: 8,
        subCategoryName: 'Bluechips',
      },
      {
        _id: '62924d4d1d9be03df7a4a747',
        subCategoryId: 9,
        subCategoryName: 'Sector Specific',
      },
    ],
    functionality: [
      {
        _id: '62924d4d1d9be03df7a4a748',
        functionalityId: {
          status: 'active',
          _id: 1,
          name: 'Long Only',
          description: 'Long Only',
        },
        functionalityName: 'Long Only',
      },
    ],
    trading_frequency: 'weekly',
    __v: 0,
    curr_stocks: [],
  },
];

export default quants;
