import image from '../assets/images/card_image.svg';
export const data = [
  {
    bank: 'Banknifty',
    quants: [
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Low',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'High',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
    ],
  },
  {
    bank: 'Nifty',
    quants: [
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
    ],
  },
  {
    bank: 'BlueChip',
    quants: [
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
    ],
  },
  {
    bank: 'Mid Cap',
    quants: [
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
    ],
  },
  {
    bank: 'Small Cap',
    quants: [
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
      {
        Image: image,
        name: 'Zeus',
        price: '150K',
        severity: 'Medium',
      },
    ],
  },
];
